export const large = {
    f2: 'https://tahmooris.s3.amazonaws.com/f2.jpg',
    l2: 'https://tahmooris.s3.amazonaws.com/l2.jpg',
    n2: 'https://tahmooris.s3.amazonaws.com/n2.jpg',
    n3: 'https://tahmooris.s3.amazonaws.com/n3.jpg',
    n4: 'https://tahmooris.s3.amazonaws.com/n4.jpg',
    n5: 'https://tahmooris.s3.amazonaws.com/n5.jpg',
    s2: 'https://tahmooris.s3.amazonaws.com/s2.jpg',
    s4: 'https://tahmooris.s3.amazonaws.com/s4.jpg',
    s6: 'https://tahmooris.s3.amazonaws.com/s6.jpg',
    s7: 'https://tahmooris.s3.amazonaws.com/s7.jpg',
    s14: 'https://tahmooris.s3.amazonaws.com/s14.jpg',
    t1: 'https://tahmooris.s3.amazonaws.com/t1.jpg',
    t2: 'https://tahmooris.s3.amazonaws.com/t2.jpg',
    t3: 'https://tahmooris.s3.amazonaws.com/t3.jpg',
    t4: 'https://tahmooris.s3.amazonaws.com/t4.jpg',
    t5: 'https://tahmooris.s3.amazonaws.com/t5.jpg',
    t6: 'https://tahmooris.s3.amazonaws.com/t6.jpg',
    t9: 'https://tahmooris.s3.amazonaws.com/t9.jpg',
    t10: 'https://tahmooris.s3.amazonaws.com/t10.jpg',
    t11: 'https://tahmooris.s3.amazonaws.com/t11.jpg',
    v1: 'https://tahmooris.s3.amazonaws.com/v1.jpg',
    v7: 'https://tahmooris.s3.amazonaws.com/v7.jpg',
    v8: 'https://tahmooris.s3.amazonaws.com/v8.jpg',
};

export const small = {
    f2: 'https://tahmooris.s3.amazonaws.com/f2.jpg',
    l2: 'https://tahmooris.s3.amazonaws.com/l2.jpg',
    n2: 'https://tahmooris.s3.amazonaws.com/n2.jpg',
    n3: 'https://tahmooris.s3.amazonaws.com/n3.jpg',
    n4: 'https://tahmooris.s3.amazonaws.com/n4.jpg',
    n5: 'https://tahmooris.s3.amazonaws.com/n5.jpg',
    s2: 'https://tahmooris.s3.amazonaws.com/s2.jpg',
    s4: 'https://tahmooris.s3.amazonaws.com/s4.jpg',
    s6: 'https://tahmooris.s3.amazonaws.com/s6.jpg',
    s7: 'https://tahmooris.s3.amazonaws.com/s7.jpg',
    s14: 'https://tahmooris.s3.amazonaws.com/s14.jpg',
    t1: 'https://tahmooris.s3.amazonaws.com/t1.jpg',
    t2: 'https://tahmooris.s3.amazonaws.com/t2.jpg',
    t3: 'https://tahmooris.s3.amazonaws.com/t3.jpg',
    t4: 'https://tahmooris.s3.amazonaws.com/t4.jpg',
    t5: 'https://tahmooris.s3.amazonaws.com/t5.jpg',
    t6: 'https://tahmooris.s3.amazonaws.com/t6.jpg',
    t9: 'https://tahmooris.s3.amazonaws.com/t9.jpg',
    t10: 'https://tahmooris.s3.amazonaws.com/t10.jpg',
    t11: 'https://tahmooris.s3.amazonaws.com/t11.jpg',
    v1: 'https://tahmooris.s3.amazonaws.com/v1.jpg',
    v7: 'https://tahmooris.s3.amazonaws.com/v7.jpg',
    v8: 'https://tahmooris.s3.amazonaws.com/v8.jpg',
};
